---
title: "Linux assignment"
author: "Trent Gutierrez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Q1: What is your home directory?

A1:`pwd` returns */home/ec2-user*


Q2: What is the output of this command?

A2: `ls` returns *hello_world.txt*


Q3. What is the output of each `ls` command?

A3: `ls my_folder` returns nothing
    `ls my_folder2` returns *hello_world.txt*


Q4: What is the output of each?

A4: `ls my_folder` returns nothing
    `ls my_folder3` returns nothing
    `ls my_folder3` returns *hello_world.txt*


Q5: What editor did you use and what was the command to save your file changes?

A5: `nano hello_world.txt` and then changed "world" to "Linux" and used ctrl-x  
    to exit and saved my changes with y, and left the file's name alone. 

Q6. What is the error?
A6: Server refused our key 
    No Supported authentication methods available

Q7. What was the solution?
A7: The solution to this problem was to: 
    - Create a new key pair for a new pem file
    - Import the pem file to my local Ubuntu env, using MobaXterm's import feature
    - Right click the pem file and adjust the settings to be more secure (400, user read only)
    - Now on another tab, connect via ec2-user 
    - (Sudouser should be created and password protected) 
    - switch to the sudouser
    - create the .ssh directory 
    - adjust permissions of the folder to 700
    - create a file named "authorized_keys" 
    - adjust this file's permissions to 600
    - nano the key file 
    - back on Ubuntu: extract the public key from the private pem file
    - copy and paste this string into the key nano 
    - save key file 
    - Now sudouser should be allowed to connect using the new pem key and be password protected. 
    
Q8.1 what does the sudo docker run part of the command do? 
A8.1
1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.


Q8.2 and what does the salmon swim part of the command do? 
A8.2:  swim : perform super-secret operation, I'm pretty sure this just prints out the salmon fancy text. 


Q9. What is the output of this command?
A9: serveruser is not in the sudoers file.  This incident will be reported.

Q10. What is the output of flask --version?
A10:

Python 3.9.12
Flask 2.1.3
Werkzeug 2.0.3


Q11. What is the output of mamba -V?
A11: conda 22.9.0

Q12. What is the output of which python?
A12: /home/serveruser/miniconda3/envs/py27/bin/python

Q13. What is the output of which python now?
A13:/home/serveruser/miniconda3/bin/python

Q14. What is the output of salmon -h?
A14: salmon v1.4.0

Usage:  salmon -h|--help or
        salmon -v|--version or
        salmon -c|--cite or
        salmon [--no-version-check] <COMMAND> [-h | options]

Commands:
     index      : create a salmon index
     quant      : quantify a sample
     alevin     : single cell analysis
     swim       : perform super-secret operation
     quantmerge : merge multiple quantifications into a single file
(salmonEnv) serveruser@ip-172-31-23-175:~$ salmon -h
salmon v1.4.0

Usage:  salmon -h|--help or
        salmon -v|--version or
        salmon -c|--cite or
        salmon [--no-version-check] <COMMAND> [-h | options]

Commands:
     index      : create a salmon index
     quant      : quantify a sample
     alevin     : single cell analysis
     swim       : perform super-secret operation
     quantmerge : merge multiple quantifications into a single file

Q15. What does the -o athal.fa.gz part of the command do?
A15: -o specifies our output of the download

Q16. What is a .gz file?
A16: it is a compressed gzip file, combines files while saving space by compressing them. 

Q17. What does the zcat command do?
A17: allows the user to expand and view a compressed file without uncompressing that file

Q18. what does the head command do?
A18: it just gives us the first (n) amount of lines in our file 

Q19. what does the number 100 signify in the command?
A19: we want to see 100 lines from the athal.fa.gz file

Q20. What is | doing? -- Hint using | in Linux is called "piping"
A20: It is separating the two commands we wrote in our 1 line, first the zcat command will run and then immediately the head command will look at our athal data. 

Q21. What is a .fa file? What is this file format used for?
A21: it is a fasta file format and contains our raw sequencing data. 

Q22. What format are the downloaded sequencing reads in? 
A22: prefetch should acquire the SRA Normalized Format file for our files, which is our FASTQ-files. 

Q23. What is the total size of the disk?
A23: 7.6Gb 

Q24. How much space is remaining on the disk?
A24: 1.8Gb

Q25. What went wrong?
A25:  fastq-dump.3.0.0 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4' repeated. error code 3

Q26: What was your solution? 
A26: $fastq-dump --gzip --skip-technical --clip SRR074122










